import fs from 'node:fs';
import {metrics,isEarlyWatch} from '../api/scan.js';
const symbols=(process.env.BACKTEST_SYMBOLS||'RY.TO,TD.TO,BMO.TO,BNS.TO,CM.TO,NA.TO,SHOP.TO,CSU.TO,OTEX.TO,LUN.TO,ABX.TO,AEM.TO,CNQ.TO,SU.TO,CVE.TO,IMO.TO,CNR.TO,CP.TO,WCN.TO,FTS.TO,EMA.TO,T.TO,BCE.TO,TRP.TO,ENB.TO,ATD.TO,DOL.TO,L.TO,MRU.TO,QSR.TO,CCO.TO,NTR.TO,POW.TO,MFC.TO,SLF.TO,GWO.TO,BN.TO,BAM.TO,WSP.TO,STN.TO,TFII.TO,MG.TO,GIB-A.TO,AAPL.TO,MSFT.TO,NVDA.TO,AMZN.TO,GOOG.TO,META.TO,TSLA.TO').split(',').map(x=>x.trim()).filter(Boolean);
const range=process.env.BACKTEST_RANGE||'2y',horizons=(process.env.BACKTEST_HORIZONS||process.env.BACKTEST_HORIZON||'5,10,20').split(',').map(Number).filter(x=>x>0),maxH=Math.max(...horizons),minDollar=Number(process.env.BACKTEST_MIN_DOLLAR||5000000),warmup=90;
const CDR=new Set(['AAPL.TO','MSFT.TO','NVDA.TO','AMZN.TO','GOOG.TO','META.TO','TSLA.TO','AMD.TO']);
const benchSymbol=s=>CDR.has(s)?'^IXIC':'^GSPTSE',dayKey=t=>new Date(t*1000).toISOString().slice(0,10);
const round=(n,d=2)=>Number.isFinite(n)?Number(n.toFixed(d)):null,pct=(a,b)=>Number.isFinite(a)&&Number.isFinite(b)&&b?((a/b)-1)*100:null;
async function fetchRows(symbol){const url=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=${range}&interval=1d&includePrePost=false&events=div%2Csplits`;const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 MarketHunterBacktest/1.0'}});if(!r.ok)throw new Error(`${symbol}: HTTP ${r.status}`);const j=await r.json(),z=j?.chart?.result?.[0],q=z?.indicators?.quote?.[0]||{},adj=z?.indicators?.adjclose?.[0]?.adjclose||q.close||[];return(z?.timestamp||[]).map((t,i)=>({t,close:adj[i],rawClose:q.close?.[i],high:q.high?.[i],low:q.low?.[i],volume:q.volume?.[i]})).filter(x=>[x.close,x.rawClose,x.high,x.low,x.volume].every(Number.isFinite)&&x.volume>0)}
function align(rows,date){const i=rows.findIndex(x=>dayKey(x.t)===date);return i>=0?rows.slice(0,i+1):null}
function setups(m,stage){const o=[];if(m.nearRecentLow===true&&(m.sellingPressureFading===true||m.downsideSlowing===true)&&m.ret20<0)o.push('Selling Exhaustion');if(stage==='Recovery')o.push('Recovery');if(m.higherLow===true&&Number.isFinite(m.momentumShift)&&m.momentumShift>0)o.push('Higher-Low Turn');if(m.highState==='local_high_broken')o.push('Local Breakout');if(m.weeklyUp===true&&m.dailyUp===true&&m.pullback<=-2&&m.pullback>=-12)o.push('Pullback in Uptrend');if(m.lowState==='failed_low_break')o.push('Failed Breakdown / Reclaim');return o}
function summary(a){if(!a.length)return null;const r=a.map(x=>x.forwardReturn),v=[...r].sort((a,b)=>a-b),m=Math.floor(v.length/2);return{n:r.length,positiveRate:round(r.filter(x=>x>0).length/r.length*100,1),gain7Rate:round(r.filter(x=>x>=7).length/r.length*100,1),loss7Rate:round(r.filter(x=>x<=-7).length/r.length*100,1),mean:round(r.reduce((a,b)=>a+b,0)/r.length),median:round(v.length%2?v[m]:(v[m-1]+v[m])/2)}}
const needed=[...new Set([...symbols,...symbols.map(benchSymbol)])],data={};for(const s of needed){process.stdout.write(`fetch ${s}... `);try{data[s]=await fetchRows(s);console.log(data[s].length)}catch(e){console.log('SKIP',e.message);data[s]=[]}}
const events=[];for(const symbol of symbols){const rows=data[symbol],bench=data[benchSymbol(symbol)];if(!rows?.length||!bench?.length)continue;for(let i=warmup;i<rows.length-maxH;i++){const hist=rows.slice(0,i+1),date=dayKey(rows[i].t),bh=align(bench,date);if(!bh||bh.length<65)continue;const m=metrics({rows:hist},{rows:bh},null);if(!m||!Number.isFinite(m.avgDollarVol)||m.avgDollarVol<minDollar||rows[i].rawClose<2)continue;const stage=m.stage||(isEarlyWatch(m)?'Early Watch':null);if(!stage)continue;for(const horizon of horizons){const forwardReturn=pct(rows[i+horizon].close,rows[i].close),benchEntry=bh.at(-1)?.close,benchFuture=bench.find(x=>dayKey(x.t)===dayKey(rows[i+horizon].t))?.close,benchmarkReturn=pct(benchFuture,benchEntry);events.push({symbol,date,horizon,stage,setups:setups(m,stage),entry:round(rows[i].close),exit:round(rows[i+horizon].close),forwardReturn:round(forwardReturn),benchmarkReturn:round(benchmarkReturn),excessReturn:round(Number.isFinite(benchmarkReturn)?forwardReturn-benchmarkReturn:null),momentumShift:m.momentumShift,rs20:m.rs20,roomToResistance:m.roomToResistance})}}}
const byHorizon={};for(const horizon of horizons){const he=events.filter(e=>e.horizon===horizon),byStage={},bySetup={};for(const e of he){(byStage[e.stage]??=[]).push(e);for(const x of e.setups)(bySetup[x]??=[]).push(e)}byHorizon[String(horizon)]={overall:summary(he),byStage:Object.fromEntries(Object.entries(byStage).map(([k,v])=>[k,summary(v)])),bySetup:Object.fromEntries(Object.entries(bySetup).map(([k,v])=>[k,summary(v)])),benchmarkBeatRate:round(he.filter(e=>Number.isFinite(e.excessReturn)&&e.excessReturn>0).length/Math.max(1,he.filter(e=>Number.isFinite(e.excessReturn)).length)*100,1),meanExcessReturn:round(he.filter(e=>Number.isFinite(e.excessReturn)).reduce((a,e)=>a+e.excessReturn,0)/Math.max(1,he.filter(e=>Number.isFinite(e.excessReturn)).length))}}
const result={generatedAt:new Date().toISOString(),range,horizons,minDollar,symbols,validSymbols:symbols.filter(x=>data[x]?.length),totalEvents:events.length,byHorizon,events};fs.mkdirSync('data',{recursive:true});fs.writeFileSync('data/backtest.json',JSON.stringify(result,null,2)+'\n');console.log('\nBACKTEST',JSON.stringify({...result,events:undefined},null,2));
